### ISSUE TITLE
memory writes in macros

### ISSUE THREAD

**Issue by mumbel** [esaulenka/Ghidra_C166#1]
@esaulenka   Hadn't ever seen that you wrote this, but came across it on /r/reverseengineering.  

I don't have any binaries to test this, but it looks like your approach might be doing weird things with memory writes.   For example in `add`, it would maybe read the value in `mem1631_w` and use it in the macro and then try to write to that value instead of writing to `export *:2 mem1631`.  Curious if this sort of change would improve things.

```
:add mem1631_w, r0815 is op0007=0x04 & r0815 ; mem1631_w {
	add_w (mem1631_w, r0815);
}
```

```
:add mem1631_w, r0815 is op0007=0x04 & r0815 ; mem1631_w {
	local tmp = mem1632_w;
	add_w (tmp, r0815);
	mem1632_w = tmp;
}
```

**Comment by mumbel** [comment]
now I'm not certain after thinking about it a bit more.  I may be confusing this with another syntax issue I've seen.  directly using the memory access for the macro, not an export:  ie  `add_w(*:2 mem1631, r0815)`

**Comment by esaulenka** [comment]
Hello, glad to see you here!

I will check your suggestion slightly later, thanks.

If you want to do some tests, you can use these binaries: [modern Lada M86 fw](https://chiptuner.ru/content/ser_m86/), [old Lada M75 fw](https://chiptuner.ru/content/ser_m75/)
Some of that files is crypted, you need `.bin` ones, it contans raw dumps.
These units built with Infineon XC2765 (old) XC2768 (new).

I am tested ghidra with [I785XMI7](https://chiptuner.ru/wp-content/firmware/M86/I785XMI7.rar), memory map can be obtained [here](https://www.infineon.com/dgdl/Infineon-SAK-XC2768X-136F128LR%20AA-DS-v01_03-EN.pdf?fileId=5546d46249cd10140149eb94e4e3318c).

But now main difficulty is in `EXTP` instruction, which should modify several subsequent instrutions.
I am described it in main [ghidra github](https://github.com/NationalSecurityAgency/ghidra/issues/1290), but I cant find suitable solution.

**Comment by esaulenka** [comment]
Current syntax looks correct:
```
          cead32         05  8f  d3  5f             addb       DAT_001fd3 ,ONES
```
```
DAT_001fd3 = DAT_001fd3 + -1;
```
(I785XMI7 at 0xCEAD32)

**Comment by mumbel** [comment]
yeah, I'm guessing my reading/analysis was wrong of your code, thanks for the binaries, will do another read through with the example up
