### ISSUE TITLE
PSW flags might be wrong

### ISSUE THREAD

**Issue by rnd-ash** [esaulenka/Ghidra_C166#17]
Using [this pdf](https://www.keil.com/dd/docs/datashts/infineon/c166ism.pdf) as a reference.

For most PSW update functions, the data sheet states the following:

```
E: Set if the value of op2 represents the lowest possible negative
number. Cleared otherwise. Used to signal the end of a table.
```

In the sleigh code I see:
```
macro setE_b(x)		{ $(PSW_E) = (x == 0xFF); }
macro setE_w(x)		{ $(PSW_E) = (x == 0xFFFF); }
```

shouldn't these values be 0x80 or 0x8000 respectively?  Lowest negative number should be just the sign set to 1, and everything else set to 0. 0xFF and 0xFFFF is just -1

(Accidentally found this discrepancy trying to write an emulator for the C167CS CPU)

**Comment by esaulenka** [comment]
oh! Yes, you are right
