### ISSUE TITLE
Trying to decompile Visteon DCU 101 (ST10F276 ) 

### ISSUE THREAD

**Issue by Vectadeus** [esaulenka/Ghidra_C166#18]
I have downloaded this repository and added in ghidra, trying to analyse this ECU's frimeware but it is not being analysed, am I doing something wrong ? Can you please somehow give me direction ? Thank you.

**Comment by esaulenka** [comment]
What exactly did you do?
Do you see a new 'language' when you adding your binary?

**Comment by Vectadeus** [comment]
Yes , I have figured it out, ghidra did not automaticly start decompiling it, I have managed to make ghidra work by finding specific and started decompiling from there
