### ISSUE TITLE
ZEROS and ONES - a very special SFRs

### ISSUE THREAD

**Issue by esaulenka** [esaulenka/Ghidra_C166#3]
they always returns constant value

sample: FUN_cef674, LAB_cf22fe

**Comment by mumbel** [comment]
ohhhh, ... I should have caught that, sorry

Will need to add ZEROS and ONES back to the special register list and fixup pspec
and then make special conditions like you had before for those to export 0 or 0xffff

I can work on that this weekend if you havent fixed yet

**Comment by esaulenka** [comment]
dont worry, i did it
