### ISSUE TITLE
jmpXX with cc_UC is a special case

### ISSUE THREAD

**Issue by esaulenka** [esaulenka/Ghidra_C166#6]
now unconditinal branch disassembled sligtly ugly:
` c03578 0d  02           jmpr       cc_UC,LAB_c0357e`
transforms to `if (true) ....`

**Comment by flarn2006** [comment]
It also shows up as a branch in the function graph. There's a red arrow going from the unconditional jump to the instruction immediately after it, even though no such path exists. It makes the graph misleading and harder to follow.

**Comment by esaulenka** [comment]
should be fixed by https://github.com/esaulenka/Ghidra_C166/commit/8208da775fea03df7d4ca024416316a5d8787f50
